import os

def build_css():
    # Base directory for CSS
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'static', 'css'))
    
    # List of CSS files in order of concatenation
    css_files = [
        'base/_variables.css',
        'base/_reset.css',
        'layout/_sidebar.css',
        'layout/_header.css',
        'layout/_dashboard.css',
        'components/_buttons.css',
        'components/_forms.css',
        'components/_badges.css',
        'components/_cards.css',
        'components/_modals.css',
        'components/_stepper.css',
        'components/_confirmation.css',
        'components/_data_viz.css',
        'components/_toast.css',
        'components/_reports.css',
        'pages/_login.css',
        '_utilities.css'
    ]
    
    output_file = os.path.join(base_dir, 'bundle.css')
    
    print(f"Building CSS bundle at {output_file}...")
    
    with open(output_file, 'w', encoding='utf-8') as outfile:
        outfile.write("/* ============================================================\n")
        outfile.write("   BRAJHER'S CAKE — Bundled Stylesheet\n")
        outfile.write("   Auto-generated by scripts/build_css.py\n")
        outfile.write("   ============================================================ */\n\n")
        
        for file in css_files:
            file_path = os.path.join(base_dir, file.replace('/', os.sep))
            if os.path.exists(file_path):
                print(f"Adding {file}...")
                with open(file_path, 'r', encoding='utf-8') as infile:
                    outfile.write(f"/* --- Source: {file} --- */\n")
                    outfile.write(infile.read())
                    outfile.write("\n\n")
            else:
                print(f"Warning: File {file_path} not found. Skipping.")
                
    print("CSS bundling complete.")

if __name__ == "__main__":
    build_css()
